### ISSUE TITLE
Questions from Steel Supplier

### ISSUE THREAD

**Issue by theoryshaw** [OpeningDesign/Lake_Kegonsa_Home#12]
Hey @bausk 

Could you answer the following couple questions from the steel supplier?  Particularly questions (3) and (4).
Associated documents can be found here: https://github.com/OpeningDesign/Lake_Kegonsa_Home/commit/a5925e1124955b8893b7d240e0124c62587f89c9
or..
Lake_Kegonsa_Home\Transfer\Endres Mfg_20141222

>Before we make up a drawing for approval, please clarify.
 1)      We will be making the steel columns, using 3” sch. 40 pipe. We do have adjustable base for these, similar to the FHA posts.

I'm assuming this is okay.
> 2)      W12x28 – Your choice will be W12x26 or W12x30.

they read the plan wrong, it 'is' a W12x26.  It's the beam along H
>3)      L8x4x9/16” is not made. We have in stock L8x4x1/2 and I attached the mill certs with it. About 53 KSI. Can you make this work?

>4)      There is a double LVL connecting to the L8x4. Toby mentioned it would be difficult to determine exact location. Can you draw up some type of plate hanger similar to what I attached that would work. Toby said he would like to field drill the location into the L8x4.

**Comment by bausk** [comment]
Ryan,
the initial sketch is okay to go but according to the IFC model, the LVL joists approach the lintel beam 2 3/4" lower compared bottom to bottom. I have added minor changes to the sketch to account for that, please view here:

https://github.com/OpeningDesign/Lake_Kegonsa_Home/commit/fbfa3e27eb721e9ff663f5c334403d16d1fea6b1

Since it is better practice to attach wood in the lower part of the section to prevent splintering, the mount holes for the LVL should be in the lower part of the LVL section.

Otherwise the sketch for question 4 is okay to go.

**Comment by theoryshaw** [comment]
Thanks Alex
